# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


FACEBOOK_APP_KEY: '3031368753769688' #gibberish
FACEBOOK_APP_SECRET: '88888c9ac313cffe047a8be7420d32e9' #gibberish

aws_access_key_id: 'XXIAIXQSJNQDPMJDQA4X' #gibberish
aws_secret_access_key: 'ERfZDuJ4XxMYKug3nRXJdwCxERUmTGCD5N8XV2xO' #gibberish

BRAINTREE_MERCHANT_ID: '8gXxbvqtdXdXXshX'
BRAINTREE_PUBLIC_KEY: 'vs3wXXXX689kbyvn'
BRAINTREE_PRIVATE_KEY: 'f0e6a1f3XXXXXa7e78adc15f6fe7d21ac'

MAILER_EMAIL: 'XXXX@gmail.com'
MAILER_PASSWORD: 'XxxxX'

MAILER_MAIL: 'why@gmail.com'
MAILER_PASSWORD: 'XxxxX'
